name = "EventPlannerPro"
license = "Apache-2.0"
licenselink = ""
description = ""

# The home page of the theme, where the source can be found.
homepage = ""

# If you have a running demo of the theme.
demosite = ""

tags = []
features = []

min_version = "0.104.0"

# If the theme has a single author
[author]
    name = ""
    homepage = ""

# If porting an existing theme
[original]
  name = ""
  author = ""
  homepage = ""
  repo = ""